### ISSUE TITLE
FEAT/ Swap current daily combo JSON system.

### ISSUE THREAD

**Issue by Sanlovty** [AnisovAleksey/HamsterKombatBot#1]
### Предлагаю изменить способ доставки daily-combo клиентам бота, путём замены hard-coded json файла на api

В оригинальном репо создали [issue](https://github.com/shamhi/HamsterKombatBot/issues/225) в котором один из парней развернул [API](https://github.com/shamhi/HamsterKombatBot/issues/225#issuecomment-2155370580), и сказал, что будет следить за обновлением. Чтобы каждый день не фетчить новую json'ку для получения нового комбом, предлагаю просто юзать APi этого парня, которое он сделал.  _Думаю, можно даже согласовать с владельцем api, если это очень сильно волнует._

**Comment by AnisovAleksey** [comment]
в чем смысл?) он его так же обновляет. Если бы программно можно было как-то найти комбо то это другой разговор)

**Comment by AnisovAleksey** [comment]
Так и сейчас не придется. json в репе лежит чтобы хостить его через github pages.
Бот забирает актуальный json по ссылке https://anisovaleksey.github.io/HamsterKombatBot/daily_combo.json

**Comment by KOTBCTAKAHE** [comment]
> в чем смысл?) он его так же обновляет. Если бы программно можно было как-то найти комбо то это другой разговор)

чтобы вы не мучались, можете и мой апи использовать, а так, я не настаиваю))0)

**Comment by KOTBCTAKAHE** [comment]
просто иногда, вы можете чуть позже его выложить
