### ISSUE TITLE
[QUESTION] Логика покупки комбо карт

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#11]
В первую очередь спасибо за отличную реализацию логики покупки и апгрейда карточек. Возник вопрос по поводу работы логики покупки комбо карточек:

1. Просчитывается ли выгодность покупки комбо (например, стоимость выкупа всех комбо карт превышает профит, который будет получен по итогу)?
2. Если невозможно купить хотя бы одну карту из трёх (по разным причинам), будет ли он покупать доступные карты, несмотря на это?
3. Если задан неприкосновенный баланс, будет ли он его тратить на покупку комбо (имеет смысл, если вырученные 5 млн покроют стоимость выкупа комбо)?

**Comment by AnisovAleksey** [comment]
Выше ответили все верно) посчитать выгодность комбо можно, но надо ли оно?) как будто оно будет выгодным почти всегда, накиньте обратные примеры, если есть.

**Comment by Yorksik** [comment]
> Выше ответили все верно) посчитать выгодность комбо можно, но надо ли оно?) как будто оно будет выгодным почти всегда, накиньте обратные примеры, если есть.

Сегодняшнее комбо для меня немного выгоднее чем самая выгодная карта.

сумма, потраченная на 3 карты за вычетом 5кк, разделенная на сумму прибылей в час от комбокарт должна быть выгоднее чем самая выгодная карта.

все сильно зависит от того какие комбо карты выпадут!

**Comment by AnisovAleksey** [comment]
вопрос не в этом, а в том нужно ли проверять выгодность комбо?

**Comment by dntaya** [comment]
> вопрос не в этом, а в том нужно ли проверять выгодность комбо?

имхо нет, так ка тут стратегия - тупо покупай карточки, сколько бы они не стоили.
единственные риски, что могут появится карточки в спешиал с кротким сроком жизни, или тогда в общей очереди она просто не успеет купится

**Comment by dntaya** [comment]
> вопрос не в этом, а в том нужно ли проверять выгодность комбо?

единственное, что нужно проверять - это если в комбо карта с profitPerHourDelta = 0 - ее стоимость должна быть меньше профита от комбо

**Comment by Yorksik** [comment]
Как в коде реализован запрос на актуальные комбо карты и шифры. откуда бот знает какие карты для комбо выбирать и какой шифр тапать?

**Comment by AnisovAleksey** [comment]
> Как в коде реализован запрос на актуальные комбо карты и шифры. откуда бот знает какие карты для комбо выбирать и какой шифр тапать?

комбо карты запрашиваются по ссылке https://anisovaleksey.github.io/HamsterKombatBot/daily_combo.json
шифр достается из запроса config'а на каждой итерации бота

**Comment by Yorksik** [comment]
> > Как в коде реализован запрос на актуальные комбо карты и шифры. откуда бот знает какие карты для комбо выбирать и какой шифр тапать?
> 
> комбо карты запрашиваются по ссылке https://anisovaleksey.github.io/HamsterKombatBot/daily_combo.json шифр достается из запроса config'а на каждой итерации бота

Спасибо за ответ.

Если в репозиторий обновится, докер образ пересоберется сам или нужно сделать pull и пересобрать руками?

**Comment by AnisovAleksey** [comment]
ну сам он точно не пересоберется)

**Comment by Yorksik** [comment]
> ну сам он точно не пересоберется)

ок. спасибо. думал как в кубере если в репо поменял, то новый образ сам развернется в докере.

P.S. Сори за глупые вопросы. Я только учусь)

**Comment by XPacL** [comment]
Чем выше уровень, тем меньше смысла в покупке комбо. У меня сейчас карты ценой по 20-40 млн каждая, и в преддверии скорого (как говорят) листинга эти средства лучше вкладывать в максимально выгодные карточки вместо комбо. Достаточно было бы сделать опцию отключения автопокупки комбо.

**Comment by anotheron1** [comment]
> Чем выше уровень, тем меньше смысла в покупке комбо. У меня сейчас карты ценой по 20-40 млн каждая, и в преддверии скорого (как говорят) листинга эти средства лучше вкладывать в максимально выгодные карточки вместо комбо. Достаточно было бы сделать опцию отключения автопокупки комбо.

В целом, да, всё так. Но проверка выгодности способствует автоматизации процесса

**Comment by Yorksik** [comment]
> > вопрос не в этом, а в том нужно ли проверять выгодность комбо?
> 
> Мне кажется, да. Вот сейчас комбо:
> 
> 1. Meme coins (lvl 17) - 8,002,226 / 347 = 23,061
> 2. IT team (lvl 17) - 8,002,226 / 758 = 10,557
> 3. Web3 academy launch (lvl 16) - 18,287,997 / 4,420 = 4,137
>    Саммари - (34,292,449 - 5,000,000) / 5,525 = 5,301
> 
> И возьмём карточку из спешл Consensus Piranha Pass (lvl 14) - 16,614,856 / 4,890 = 3,397 И подобных много

действительно, покупка комбо стала сильно невыгодна.

если есть возможность реализовать проверку на выгодность приобретения карт из комбо, было бы круто

расчет предлагаю такой(на примере поста выше):
если среднаяя доходность комбокрт меньше суммы карт с наивысшей доходностью => комбо не покупать

по примеру из поста выше
Meme coins (lvl 17) -                     8,002,226                             / 347       = 23,061
IT team (lvl 17) -                             8,002,226                             / 758       = 10,557
Web3 academy launch (lvl 16) - 18,287,997                              / 4,420    = 4,137
                                                       (34,292,449 - 5,000,000)    / 5,525     = 5,301

итого если у нас. есть карта(ы) с доходностью выше чем 5,301 которые в сумме будут приность больше в час чем 5,525 => комбо не выгодно
