### ISSUE TITLE
не запускается бот

### ISSUE THREAD

**Issue by Yorksik** [AnisovAleksey/HamsterKombatBot#15]
Подскажите пожалуйста от чего не запускается бот ни в консоле ubuntu  ни в докере.
Вот такая ошибка!

<img width="561" alt="image" src="https://github.com/AnisovAleksey/HamsterKombatBot/assets/17272516/18dfc8c0-4d95-4da8-8f4f-9a80debfd043">

**Comment by AnisovAleksey** [comment]
зарегистрированных клиентов нет

**Comment by Yorksik** [comment]
хм вот новая ошибка 
я так понимаю с питоном у меня что то не так. библиотеку не может найти
<img width="687" alt="image" src="https://github.com/AnisovAleksey/HamsterKombatBot/assets/17272516/d0f11ee9-0003-4e5f-bc2b-645acd493bff">

**Comment by AnisovAleksey** [comment]
Питон 3.11 нужен, у тебя 3.10
