### ISSUE TITLE
[QUESTION] Как можно отключить автопокупку комбо карт?

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#17]

**Comment by AnisovAleksey** [comment]
никак, только если полностью апгрейды выключить, а в чем смысл выключать это?

**Comment by XPacL** [comment]
Ну просто бывает сумма покупки всех трёх карт 15млн, а профита оттуда 5млн. И прироста в час эти карты карты дают хрен да маленько. В итоге в минус уходим. Ингода прокачка комбо не целесообразна.

**Comment by AnisovAleksey** [comment]
я попробую добавить рассчет выгодности комбо, но мне надо где-то реферальные значения брать для понимания границы от которой комбо будет считаться выгодным. Например 5% отклонение от самой выгодной карты на данный момент? процент я имею ввиду от окупаемости карточек. т.е. если окупаемость самой выгодной карты 1600 часов, а окупаемость комбо 1680, то комбо будет считаться выгодным. При окупаемости > 1680 комбо будет считаться не выгодным и пропускаться

**Comment by XPacL** [comment]
Справедливо

> > я попробую добавить рассчет выгодности комбо, но мне надо где-то реферальные значения брать для понимания границы от которой комбо будет считаться выгодным. Например 5% отклонение от самой выгодной карты на данный момент? процент я имею ввиду от окупаемости карточек. т.е. если окупаемость самой выгодной карты 1600 часов, а окупаемость комбо 1680, то комбо будет считаться выгодным. При окупаемости > 1680 комбо будет считаться не выгодным и пропускаться
> 
> Мышиная возня имхо. Он все равно купит эти карты, тк карты обновятся очень редко. Не в этой итерации так в след. Но тут он бонусом получает 5 000 000 которые ограничены во времени. Все норм, ничего менять не нужно

Ну по идее да, если подумать, то много не выиграешь с этого. Пусть остаётся как есть.
