### ISSUE TITLE
Q/ Миграция сессий с оригинального repo

### ISSUE THREAD

**Issue by Sanlovty** [AnisovAleksey/HamsterKombatBot#2]
Перенос `sessions` с оригинального repo путём решения в лоб ( простым перемещением папки) не работает. Есть ли вообще возможность миграции сессий  и, если да, то какая?

**Comment by AnisovAleksey** [comment]
не было времени миграцию реализовать, но на самом деле лучше тот способ авторизации не использовать, т.к. там не верно упаковываются данные для авторизации и если создатели хомяка захотят - легко найдут всех ботов) 

Самый лучший вариант выдергивать токен с реального девайса

**Comment by AnisovAleksey** [comment]
Выдернуть токен на iOS можно с помощью WebInspector в Safari. На андроид - не разбирался.
Этот токен потом и используется для создания клиента

**Comment by AnisovAleksey** [comment]
в любом случае - миграцию допилю, но может быть не в ближайшие дни) Если хочешь сейчас прям как-то мигрировать то можно запустить бота из оригинальной репы и в коде расставить принты токена, который вставляется в хедеры запросов. Потом с этими токенами создаешь клиентов тут

**Comment by AnisovAleksey** [comment]
ну вот какая-то статья описывает что за токен)
https://ru.hexlet.io/qna/glossary/questions/bearer-token-chto-eto#:~:text=Bearer%2Dтокен%20—%20это%20тип%20авторизационного,для%20доступа%20к%20защищенным%20ресурсам.

**Comment by AnisovAleksey** [comment]
@Sanlovty Добавил миграцию старых сессий в текущий формат
