### ISSUE TITLE
Комбо карты

### ISSUE THREAD

**Issue by Yorksik** [AnisovAleksey/HamsterKombatBot#22]
Есть ли возможность отключить комбо карты или использовать из только если они выгодны?

**Comment by dntaya** [comment]
https://github.com/AnisovAleksey/HamsterKombatBot/issues/17

**Comment by Yorksik** [comment]
> #17

Я знаю что пока этот функционал не реализован. Но возможно автор реалезует проверку рентабельности комбо

**Comment by dntaya** [comment]
> > #17
> 
> Я знаю что пока этот функционал не реализован. Но возможно автор реализует проверку рентабельности комбо

В этом нет смысла

**Comment by XPacL** [comment]
> Есть ли возможность отключить комбо карты или использовать из только если они выгодны?

Создал pr. Пока автор не обновил, можешь взять из моего репо.

**Comment by Yorksik** [comment]
> > > #17
> > 
> > 
> > Я знаю что пока этот функционал не реализован. Но возможно автор реализует проверку рентабельности комбо
> 
> В этом нет смысла

вот тут я описал что есть смысл
https://github.com/AnisovAleksey/HamsterKombatBot/issues/11#issuecomment-2179420053

**Comment by dntaya** [comment]
> > > > #17
> > > 
> > > 
> > > Я знаю что пока этот функционал не реализован. Но возможно автор реализует проверку рентабельности комбо
> > 
> > 
> > В этом нет смысла
> 
> вот тут я описал что есть смысл [#11 (comment)](https://github.com/AnisovAleksey/HamsterKombatBot/issues/11#issuecomment-2179420053)

нет. рано или поздно бот выкупает ВСЕ доступные карточки. или вы купите их по одной потом или сейчас но бонусом 5 000 000. подумайте

**Comment by AnisovAleksey** [comment]
Вот тут реализовал, пока проверяю
https://github.com/AnisovAleksey/HamsterKombatBot/tree/daily-combo-improve

**Comment by Yorksik** [comment]
> > > > > #17
> > > > 
> > > > 
> > > > Я знаю что пока этот функционал не реализован. Но возможно автор реализует проверку рентабельности комбо
> > > 
> > > 
> > > В этом нет смысла
> > 
> > 
> > вот тут я описал что есть смысл [#11 (comment)](https://github.com/AnisovAleksey/HamsterKombatBot/issues/11#issuecomment-2179420053)
> 
> нет. рано или поздно бот выкупает ВСЕ доступные карточки. или вы купите их по одной потом или сейчас но бонусом 5 000 000. подумайте

это суждение верно при бесконечном условии бесконечного времени игры. но при наличии ограничений во времени нужно дифференцировать все переменные по времени.

вы же не качаете первую карту до "конца", потом переходите ко второй и так далее

**Comment by dntaya** [comment]
> > нет. рано или поздно бот выкупает ВСЕ доступные карточки. или вы купите их по одной потом или сейчас но бонусом 5 000 000. подумайте
> 
> это суждение верно при условии бесконечного времени игры. но при наличии ограничений во времени нужно дифференцировать все переменные по времени.
> 
> вы же не качаете первую карту до "конца", потом переходите ко второй и так далее


1. бот находится почти всегда в стадии комбо карта = текущий уровень + 1 (кроме старта, там пришлось делать рекурсию)
2. как не трудно догадаться он все равно перейдёт на уровень +1 и только какие-то копейки можно выиграть на уровне остановки
3. это мышиная возня, я даже убрал все ограничения на покупку комбо, это мало что меняет

**Comment by anotheron1** [comment]
В этом нет никакого смысла. При стоимости карточек в >20кк, на каждую из которых ты фармишь сутки, совершенно не верно бежать за карточками из комбы, особенно учитывая, что комба активна сутки. Либо у тебя всегда есть около 100кк для комбы (которой хватит на одну комбу, лол), либо ты не покупаешь их

То есть ещё раз. Наш бот в моменте взял и оценил, что вот есть карточка за 32кк, выгодная, но есть комба. Даже если она менее выгодная. И он начнет сливать бабки, сначала купит первую карту комбы за условные 25кк, потом будет пол дня копить на вторую карту комбы, потом ещё пол дня копить на третью, а комба уже сменится. И по новой. Итого ты рекурсивно покупаешь хлам не получая бонус

**Comment by Yorksik** [comment]
> В этом нет никакого смысла. При стоимости карточек в >20кк, на каждую из которых ты фармишь сутки, совершенно не верно бежать за карточками из комбы, особенно учитывая, что комба активна сутки. Либо у тебя всегда есть около 100кк для комбы (которой хватит на одну комбу, лол), либо ты не покупаешь их
> 
> То есть ещё раз. Наш бот в моменте взял и оценил, что вот есть карточка за 32кк, выгодная, но есть комба. Даже если она менее выгодная. И он начнет сливать бабки, сначала купит первую карту комбы за условные 25кк, потом будет пол дня копить на вторую карту комбы, потом ещё пол дня копить на третью, а комба уже сменится. И по новой. Итого ты рекурсивно покупаешь хлам не получая бонус

верно. но все это можно описать так

Если сумма монет на счету + доход в час* 24 часа меньше суммы комбо карты
то скипать комбо.

**Comment by dntaya** [comment]
> И он начнет сливать бабки, сначала купит первую карту комбы за условные 25кк, потом будет пол дня копить на вторую карту комбы, потом ещё пол дня копить на третью, а комба уже сменится. И по новой. Итого ты рекурсивно покупаешь хлам не получая бонус

Ответ не верный. Садись, два. 
1. Стоимость апргейда пропорциональны твоему уровню фарма в час
2. Карты обновляются редко, так что ТЫ ВСЕ РАВНО КУПИШЬ ЭТОТ ХЛАМ. Доходит?
3. Это все не важно, тк по условия айрдропа важны совсем другие показатели

**Comment by AnisovAleksey** [comment]
@Yorksik  Добавил это в ветку, которую скидывал выше

**Comment by anotheron1** [comment]
> > И он начнет сливать бабки, сначала купит первую карту комбы за условные 25кк, потом будет пол дня копить на вторую карту комбы, потом ещё пол дня копить на третью, а комба уже сменится. И по новой. Итого ты рекурсивно покупаешь хлам не получая бонус
> 
> Ответ не верный. Садись, два.
> 
> 1. Стоимость апргейда пропорциональны твоему уровню фарма в час
> 2. Карты обновляются редко, так что ТЫ ВСЕ РАВНО КУПИШЬ ЭТОТ ХЛАМ. Доходит?
> 3. Это все не важно, тк по условия айрдропа важны совсем другие показатели

Да ну брось. Могу сюда скинуть логи за неделю целую. Он ни одной наовой карточки не купил, потому что копит на комбо. Я лично захожу и покупаю что надо
"ты всё равно купишь этот хлам" - да, НО не в первую очередь. Здесь важно понимание таймменеджмента, что ли, что покупка хлама в первую очередь даст тебе просадку по накоплениям на длинной дистанции
И стоимость апгрейда пропорциональна не уровню фарма, а тупо тому количеству, что ты потратил на карточку. У меня в загашнике всё ещё валяется пара карточек за лям-два, когда большинство больше 20

**Comment by AnisovAleksey** [comment]
Изменения с расчетом комбо добавлены в мейн ветку
