### ISSUE TITLE
Обновление бота

### ISSUE THREAD

**Issue by Yorksik** [AnisovAleksey/HamsterKombatBot#26]
Будет ли автор обновлять бота?

**Comment by XPacL** [comment]
Замени во всех файлах hamsterkombat.io на hamsterkombatgame.io

**Comment by Yorksik** [comment]
> Замени во всех файлах hamsterkombat.io на hamsterkombatgame.io

замена домена поможет?

**Comment by XPacL** [comment]
Да, у меня работает после замены

**Comment by Yorksik** [comment]
> hamsterkombat.io

спасибо

**Comment by Yorksik** [comment]
<img width="793" alt="Снимок экрана 2024-07-14 в 12 52 28" src="https://github.com/user-attachments/assets/1ac7615d-513c-4eca-ad28-5c46f0d190c8">

**Comment by XPacL** [comment]
![IMG_20240714_160353](https://github.com/user-attachments/assets/deaf7e11-8582-44ac-8017-9c6690ded769)
Хз, мне помогло, работает. Может из за того, что у меня авторизация по токену... Не знаю.

**Comment by XPacL** [comment]
Удали клиенты (сессии) и заново создай, потом отпишись, помогло или нет

**Comment by Yorksik** [comment]
> ![IMG_20240714_160353](https://private-user-images.githubusercontent.com/74942604/348537527-deaf7e11-8582-44ac-8017-9c6690ded769.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTU2MTUsIm5iZiI6MTcyMDk1NTMxNSwicGF0aCI6Ii83NDk0MjYwNC8zNDg1Mzc1MjctZGVhZjdlMTEtODU4Mi00NGFjLTgwMTctOWM2NjkwZGVkNzY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDExMDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZTQ1MzlmZDA1MmIxZWJiZmZjNmJiN2UyMWY2ODc2Y2Y4ZTlmYzIyMTc5MTQ0OGZhMzMzYWQ2N2QwZDY3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RzDnKPB-EgqZExP5N-D-Q9phk7vLRpYBJT5PVSDCcSY) Хз, мне помогло, работает. Может из за того, что у меня авторизация по токену... Не знаю. Попробуй пересоздать сессии

у меня тоже по токену.
Мог бы ты обновить свой репо

**Comment by fly-a1one** [comment]
Тоже работает нормально все, просто ссылку обновил на новую

**Comment by Yorksik** [comment]
> Тоже работает нормально все, просто ссылку обновил на новую

в каких файлах?
только в этом?
 `bot/core/web_client.py`

**Comment by XPacL** [comment]
> > Тоже работает нормально все, просто ссылку обновил на новую
> 
> в каких файлах? только в этом? `bot/core/web_client.py`

Нет , во всех надо. Каждый файл открывай и меняй. Я репо только завтра смогу обновить своё, на работе. Сейчас дома не могу, занят, на быструю руку поменял всё.

**Comment by Yorksik** [comment]
> > > Тоже работает нормально все, просто ссылку обновил на новую
> > 
> > 
> > в каких файлах? только в этом? `bot/core/web_client.py`
> 
> Нет , во всех надо. Каждый файл открывай и меняй. Я репо только завтра смогу обновить своё, на работе. Сейчас дома не могу, занят, на быструю руку поменял всё. Ещё есть идеи по расчету и покупке комбо и покупке карт, которые находятся на КД, а в это время появляются новые карты с ограниченным временем, при включенной опции WAIT FOR MOST PROFIT UPGRADES. Все это хочу реализовать и проверить. А, ну и ссылку на комбо нужно будет сделать актуальную, автор, к сожалению, не обновляет давно

У тебя классная штука реализована, отключение тапов и рандомный заход с возможностью задать диапазон по времени. Как по мне больше на человека похоже.

**Comment by AnisovAleksey** [comment]
Обновил репу под новые домены
