### ISSUE TITLE
[QUESTION] Есть идеи как вытащить телеграм auth token из Android?

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#3]
Насколько я понял, единственный способ запустить этот форк - это получить auth токен из реального девайса. В связи с чем возник вопрос, а как собственно этот токен выдернуть из дейвайса на андроиде?

**Comment by AnisovAleksey** [comment]
можно и через старый способ. Пункт 3 при запуске и он тебе добавит токен через старую авторизацию в тг

**Comment by XPacL** [comment]
> можно и через старый способ. Пункт 3 при запуске и он тебе добавит токен через старую авторизацию в тг

Пробовал, не работает. Выдаёт ошибку после ввода имени сессии. 
![2024-06-09_16-25-30](https://github.com/AnisovAleksey/HamsterKombatBot/assets/74942604/bfbb3110-49a5-4717-a41d-ae382fcc2340)

**Comment by AnisovAleksey** [comment]
Ок, поправлю)
