### ISSUE TITLE
HamsterKombatBot-main\bot\core\tapper.py", line 267, in run     delay=(           ^

### ISSUE THREAD

**Issue by koff3st** [AnisovAleksey/HamsterKombatBot#37]
Traceback (most recent call last):
  File "C:\Soft\HM\HamsterKombatBot-main\bot\core\tapper.py", line 267, in run
    delay=(
          ^
          
    как фиксануть?

**Comment by darhanger** [comment]
![image](https://github.com/user-attachments/assets/08ab9230-1a63-471e-8289-d651d883d10d)

Точно такое же

**Comment by R2kip** [comment]
https://api.hamsterkombatgame.io/clicker/tap 
{"type":"validation","on":"body","found":{"availableTaps":4500,"count":567,"timestamp":1722545182.8278284}}

**Comment by R2kip** [comment]
Вероятно, это происходит потому, что бот не учитывает восстановление энергии (Вроде 3 энергии/сек).

**Comment by R2kip** [comment]
Достачно заминить стороку 194 в `/bot/core/tapper.py` на
`profile = await self.web_client.send_taps(available_energy=current_energy + int(sleep_time)*3, taps=simulated_taps)`

**Comment by darhanger** [comment]
А еще как я понял, никаких улучшений не происходит, от слова совсем.

**Comment by XPacL** [comment]
Отключите в .env автокликер, применение энергии и включите опцию ожидания наиболее выгодного апгрейда. Как временное решение, пока ошибки не будут исправлены:

**Comment by AnisovAleksey** [comment]
Поправил
