### ISSUE TITLE
Всё сломалось в связи с обновлением хомяка

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#38]
Привет. Беда после последней обновы от разработчиков хомяка, вообще ничего не работает. Планируются ли фиксы?

**Comment by R2kip** [comment]
Скажи что именно не работает

**Comment by Yorksik** [comment]
> Привет. Беда после последней обновы от разработчиков хомяка, вообще ничего не работает. Планируются ли фиксы?

пока нет решения?

**Comment by XPacL** [comment]
> > Привет. Беда после последней обновы от разработчиков хомяка, вообще ничего не работает. Планируются ли фиксы?
> 
> пока нет решения?

Пока только откат до имплемента игры
