### ISSUE TITLE
Обнова 

### ISSUE THREAD

**Issue by Yorksik** [AnisovAleksey/HamsterKombatBot#42]
[https://github.com/AnisovAleksey/HamsterKombatBot/commit/daeb92eb4301af8b3e257248ca335fa81fdfa155 ](url)

Подскажи пожалуйста MAX_PAYBACK_PERIOD это условие при котором покупается комбо?

ALWAYS_APPLY_DAILY_COMBO: bool = True
при  True будет покупать все комбо
при False только те которые проходят условие MAX_PAYBACK_PERIOD?

В ридми не нашел этого описания

**Comment by AnisovAleksey** [comment]
MAX_PAYBACK_PERIOD это вообще для обычных апгрейдов, чтобы не ждать конкретный апгрейд, а покупать все более-менее выгодные карточки. Я добавил эту опцию чтобы отключить WAIT_FOR_MOST_PROFIT_UPGRADES

**Comment by Yorksik** [comment]
> Покупка комбо упрощена. Теперь если комбо впринципе можно купить (хватает свободных денег) то при ALWAYS_APPLY_DAILY_COMBO=True - он его купит. Если же ALWAYS_APPLY_DAILY_COMBO стоит False то комбо купит ся в случае если затраты на его покупку получится возместить за день

Спасибо за разъяснение. теперь ограничение на покупку комбо только деньги. можно ли отключить вообще покупку комбо, как раньше. Или использовать "свой" MAX_PAYBACK_PERIOD для комбо

**Comment by XPacL** [comment]
> можно ли отключить вообще покупку комбо, как раньше.

Привет. Насколько я понял, можно в config.py прописать ALWAYS_APPLY_DAILY_COMBO=False и тогда комбо не будет покупаться в 99% случаях на высоких уровнях. Ну или добавить этот параметр в .env.

**Comment by AnisovAleksey** [comment]
Мож добавлю опцию для отключения комбо, но в целом сейчас этот параметр в False подразумевает, что не потратит больше дневного дохода, а такие комбо далеко не всегда бывают

**Comment by Yorksik** [comment]
> Мож добавлю опцию для отключения комбо, но в целом сейчас этот параметр в False подразумевает, что не потратит больше дневного дохода, а такие комбо далеко не всегда бывают

Отключение комбо или покупка комбо с MAX_PAYBACK_PERIOD для всего комбо было бы хорошей функцией.

Вчерашнее комбко имеет MAX_PAYBACK_PERIOD равный 11к при том что медианный PAYBACK_PERIOD по аккаунту 4.5, а самый низкий PAYBACK_PERIOD для новой карты 2k

Итого за сутки нафармилось 150кк и все были потрачены на комбо с PAYBACK_PERIOD равный 11к.

В каких случаях логика, которая сейчас реализована, отрабатывает с максимальным профитом?
