### ISSUE TITLE
Ключи к играм

### ISSUE THREAD

**Issue by Yorksik** [AnisovAleksey/HamsterKombatBot#44]
Можно ли "размазать" ввод ключей на длительный период. 
Что бы все ключи не вводились за малый промежуток времени для имитации более "человечного" поведения

**Comment by XPacL** [comment]
И, если можно, добавить маленько рандома при ожидании денег на покупку и при ожидании кулдауна карты. А то заходит и покупает строго по КД))

**Comment by Yorksik** [comment]
> И, если можно, добавить маленько рандома при ожидании денег на покупку и при ожидании кулдауна карты. А то заходит и покупает строго по КД))

У тебя уже есть имплементация новых игр?

**Comment by Yorksik** [comment]
<img width="390" alt="image" src="https://github.com/user-attachments/assets/0815de9b-aef3-4f38-97b9-538670afc3e5">
<img width="611" alt="image" src="https://github.com/user-attachments/assets/4b439859-d1b1-41b9-985f-209b9e4cc612">

**Comment by XPacL** [comment]
> > И, если можно, добавить маленько рандома при ожидании денег на покупку и при ожидании кулдауна карты. А то заходит и покупает строго по КД))
> 
> У тебя уже есть имплементация новых игр?

Добавил в своём форке все игры на сегодняшний момент.
