### ISSUE TITLE
New Achievement

### ISSUE THREAD

**Issue by Yorksik** [AnisovAleksey/HamsterKombatBot#53]
Все получили новую ачивку?

Это генератор или какая часть бота палится?

**Comment by Yorksik** [comment]
Вероятно вот это не похоже на действия человека
<img width="513" alt="image" src="https://github.com/user-attachments/assets/c5e6f17f-dbba-4a46-a7d6-ef3316d28a3d">

**Comment by XPacL** [comment]
Я не получал ничего. Что за ачивка?

**Comment by XPacL** [comment]
А всё увидел. Читерить плохо. Я пока не словил, серая у меня...

**Comment by Yorksik** [comment]
> А всё увидел. Читерить плохо. Я пока не словил, серая у меня... Hexa puzzle и свечки не играю

А все ключи собираешь?

**Comment by XPacL** [comment]
> > А всё увидел. Читерить плохо. Я пока не словил, серая у меня... Hexa puzzle и свечки не играю
> 
> А все ключи собираешь?

Нет, две разные игры не собираю всегда

**Comment by Yorksik** [comment]
ну посмотрим что это, бан или почти бан)

**Comment by XPacL** [comment]
Проверил все свои 7 веков, ни на один не прилетела, у всех серая. Кстати, на генератор ключей в env нужно поставить задержки от трёх минут и выше, в зависимости от количества сессий. Поэкспериментировать со временем. Тогда удастстя размазать получение и ввод ключей как раз примерно на день. У меня при двух сессиях на одного бота стоят events 240-360, generations 120-350. Такие задержки позволяют получить все ключи примерно за 16-18 часов.

**Comment by Yorksik** [comment]
> Проверил все свои 7 акков, ни на один не прилетела, у всех серая. Кстати, на генератор ключей в env нужно поставить задержки от трёх минут и выше, в зависимости от количества сессий. Поэкспериментировать со временем. Тогда удастстя размазать получение и ввод ключей как раз примерно на день. У меня при двух сессиях на одного бота стоят events 240-360, generations 120-350. Такие задержки позволяют получить все ключи примерно за 16-18 часов.

у меня тоже стоит задержка но как видишь на скрине вводит все за 1 секунду

**Comment by XPacL** [comment]
> > Проверил все свои 7 акков, ни на один не прилетела, у всех серая. Кстати, на генератор ключей в env нужно поставить задержки от трёх минут и выше, в зависимости от количества сессий. Поэкспериментировать со временем. Тогда удастстя размазать получение и ввод ключей как раз примерно на день. У меня при двух сессиях на одного бота стоят events 240-360, generations 120-350. Такие задержки позволяют получить все ключи примерно за 16-18 часов.
> 
> у меня тоже стоит задержка но как видишь на скрине вводит все за 1 секунду

Да, ключи активирует моментально, но можно подобрать время так, чтобы за полчаса (именно столько спит бот до проверки наличия ключей и их последующей активации) у тебя нагенирело 3-4 ключа. Вот тогда ты будешь похож более менее на человека.

**Comment by XPacL** [comment]
На твоём скрине вообще полная жопа, так быть конечно не должно, это палево прям пиздец

**Comment by XPacL** [comment]
Тоже получил на все акки)))

**Comment by Yorksik** [comment]
Интересно за что. И как вычислили
