### ISSUE TITLE
Ошибка при улучшении

### ISSUE THREAD

**Issue by fly-a1one** [AnisovAleksey/HamsterKombatBot#54]
При улучшении карты Telegram top ever появляется ошибка "Bad request". Появляется уже несколько дней, но другие карты улучшает нормально, кроме этой

![image](https://github.com/user-attachments/assets/3f63efcb-cdd5-4500-af9f-4b57a4f05a2b)

**Comment by XPacL** [comment]
Нужно быть подписанным на канал хомяка в телеге, тогда прокачает
