### ISSUE TITLE
Не логинится в связи с обновой

### ISSUE THREAD

**Issue by Yorksik** [AnisovAleksey/HamsterKombatBot#56]
Подскажите пожалуйста у всех бот не работает?? 

<img width="909" alt="image" src="https://github.com/user-attachments/assets/a4e322ed-58f3-466d-bed1-5ac81682a68d">

**Comment by XPacL** [comment]
Да. Разрабы поменяли API URL для аутентификации. В своём форке обновил. Также нужно будет вытащить новый  auth токен заново! Он тоже поменялся.

**Comment by Yorksik** [comment]
> Да. Разрабы поменяли API URL для аутентификации. В своём форке обновил. Также нужно будет вытащить новый auth токен заново! Он тоже поменялся.

хм. уже работает все, ничего не меняя.

**Comment by XPacL** [comment]
Блин странно это всё... У меня на новом api тоже работает. Не нравятся мне такие мувы перед листингом

**Comment by Yorksik** [comment]
> Блин странно это всё... У меня на новом api тоже работает. Не нравятся мне такие мувы перед листингом

ты дебаг на андроиде делал? с телефона как логинится?

**Comment by XPacL** [comment]
С телефона логинится по новому api, да, дебажил

**Comment by Yorksik** [comment]
ну видимо нужно менять. возможно так и отловят.
Тут нужно что -бы Алексей глянул))

**Comment by XPacL** [comment]
Да, было бы неплохо

**Comment by Yorksik** [comment]
> С телефона логинится по новому api и с новым токеном, да, дебажил

что ты имеешь ввиду "с новым токеном"
 вот это? 
<img width="1663" alt="image" src="https://github.com/user-attachments/assets/144b44d3-de62-4e07-a329-b8d839a421b1">

**Comment by XPacL** [comment]
Нет, это новый URL. Токен который ты достаешь по этой инструкции https://github.com/AnisovAleksey/HamsterKombatBot/blob/main/docs/android-auth-info-extraction-guide.md

**Comment by XPacL** [comment]
Или у тебя авторизация через сессию?

**Comment by Yorksik** [comment]
> Или у тебя авторизация через сессию?

через токен. и все работает. ничего не менял, просто бот ломился в закрытую дверь, я скинул скрин, но бота не выключал. сейчас все нормально работает без ошибок

**Comment by XPacL** [comment]
Ну тогда я вообще ничего не понимаю. Но это попахивает попыткой идентифицировать роботов. У шамхи в issues тоже есть обсуждение этого обновления api. Рекомендуют выключить бота на время, пока не поймут в чем дело. Возможно по старым токенам и старым api они и отслядят ботов.

**Comment by Yorksik** [comment]
@XPacL Нашел решение?
