### ISSUE TITLE
[QUESTION] Есть ли изменения в логике?

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#6]
По сравнению с оригинальным репо есть ли изменения в логике покупки карточек? Если есть, то можно вкратце простыми словами объяснить?

**Comment by AnisovAleksey** [comment]
Рассчитывается окупаемость карточки в часах. Если карточка откатывается, то время окупаемости увеличивается на время отката, тем самым понижая приоритет этой карточки. Сейчас еще добавляю увеличение времени окупаемости из-за того что на какую-то карточку тебе нужно копить деньги.
В оригинальной репе много отличий) я всю логику снес т.к. там просто куча условий, которые по идее надо вывести в формулу выгодности, что я и сделал. Так же там есть ограничение по апгрейду карточек за раз (одну итерацию), это я убрал. Ограничение покупки карточек в зависимости от уровня, тоже убрал (в этом нет смысла, если уровень выше выгоднее чем остальные уровнем ниже)
Может еще что-то забыл, но отличий много)

**Comment by XPacL** [comment]
В оригинальном репо если не хватает баланса на покупку выгодной карты, то он почему-то покупает всякую ерунду. То есть, там приходилось пользоваться так - накопил, к примеру, 15 миллионов - убрал запрет на автоапгрейд, он проапгрейдил карты, потом опять ставлю запрет, иначе будет постоянно покупать не выгодные карты. Здесь такая проблема есть?

**Comment by AnisovAleksey** [comment]
нет
