### ISSUE TITLE
Sleep 40s for recover full energy

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#7]
Спит 5 секунд для проверки energy boost, потом ждёт 40 секунд для восполнения энергии и потом тапает. И так всю дорогу. 
![2024-06-09_19-43-35](https://github.com/AnisovAleksey/HamsterKombatBot/assets/74942604/3232b444-ce72-4c50-8792-05aba781a435)
Как увеличить этот интервал? Сделать не 40 секунд, а в дипазоне 2000-2500 например?

**Comment by AnisovAleksey** [comment]
версия последняя?

**Comment by XPacL** [comment]
Да, версия последняя. Специально с нуля поставил ещё раз для проверки. Обратите внимание, что после старта у него нормальные интервалы сна и после вот этого первого сна он начинает спать по 40 секунд постоянно и далее.
![Uploading 2024-06-09_21-21-36.png…]()

**Comment by AnisovAleksey** [comment]
Поправил

**Comment by XPacL** [comment]
Спасибо! Огонь! Уже затестил изменения из dev ветки. Всё отлично работает, спит теперь спокойно.
